name: TodaysBible
description: "Today's Bible"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_mobile_ads: ^4.0.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:  # ✅ 앱 아이콘 설정
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/KorRV.json
    - assets/icon/icon.png

  fonts:
    - family: BookkMyungjo
      fonts:
        - asset: assets/fonts/BookkMyungjo_Light.ttf
          weight: 300
        - asset: assets/fonts/BookkMyungjo_Bold.ttf
          weight: 700
    - family: BookkGothic
      fonts:
        - asset: assets/fonts/BookkGothic_Light.ttf
          weight: 300
        - asset: assets/fonts/BookkGothic_Bold.ttf
          weight: 700
