buildscript {
    ext.kotlin_version = '1.9.20'

    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.9.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    subprojects {
        afterEvaluate {
            if (project.name.contains("google_mobile_ads")) {
                project.dependencies.add("implementation", "androidx.appcompat:appcompat:1.6.1")
            }
        }
    }

    repositories {
        google()
        mavenCentral()
    }
}
